export const FETCH_WALLET_REQUEST = "FETCH_WALLET_REQUEST";
export const FETCH_WALLET_SUCCESS = "FETCH_WALLET_SUCCESS";
export const FETCH_WALLET_FAILURE = "FETCH_WALLET_FAILURE";

export const FETCH_TRANSACTIONS_REQUEST = "FETCH_TRANSACTIONS_REQUEST";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAILURE = "FETCH_TRANSACTIONS_FAILURE";

export const CREATE_PAYMENT_LINK_REQUEST = "CREATE_PAYMENT_LINK_REQUEST";
export const CREATE_PAYMENT_LINK_SUCCESS = "CREATE_PAYMENT_LINK_SUCCESS";
export const CREATE_PAYMENT_LINK_FAILURE = "CREATE_PAYMENT_LINK_FAILURE";

export const WALLET_TRANSFER_REQUEST = "WALLET_TRANSFER_REQUEST";
export const WALLET_TRANSFER_SUCCESS = "WALLET_TRANSFER_SUCCESS";
export const WALLET_TRANSFER_FAILURE = "WALLET_TRANSFER_FAILURE";

export const WALLET_DEPOSIT_REQUEST = "WALLET_DEPOSIT_REQUEST";
export const WALLET_DEPOSIT_SUCCESS = "WALLET_DEPOSIT_SUCCESS";
export const WALLET_DEPOSIT_FAILURE = "WALLET_DEPOSIT_FAILURE";

