export const FETCH_PAYMENT_DETAILS_REQUEST = "FETCH_PAYMENT_DETAILS_REQUEST";
export const FETCH_PAYMENT_DETAILS_SUCCESS = "FETCH_PAYMENT_DETAILS_SUCCESS";
export const FETCH_PAYMENT_DETAILS_FAILURE = "FETCH_PAYMENT_DETAILS_FAILURE";

export const ADD_PAYMENT_DETAILS_REQUEST = "ADD_PAYMENT_DETAILS_REQUEST";
export const ADD_PAYMENT_DETAILS_SUCCESS = "ADD_PAYMENT_DETAILS_SUCCESS";
export const ADD_PAYMENT_DETAILS_FAILURE = "ADD_PAYMENT_DETAILS_FAILURE";

