export const FETCH_ASSETS_REQUEST = "FETCH_ASSETS_REQUEST";
export const FETCH_ASSETS_SUCCESS = "FETCH_ASSETS_SUCCESS";
export const FETCH_ASSETS_FAILURE = "FETCH_ASSETS_FAILURE";

export const FETCH_ASSET_BY_COIN_REQUEST = "FETCH_ASSET_BY_COIN_REQUEST";
export const FETCH_ASSET_BY_COIN_SUCCESS = "FETCH_ASSET_BY_COIN_SUCCESS";
export const FETCH_ASSET_BY_COIN_FAILURE = "FETCH_ASSET_BY_COIN_FAILURE";

